### ISSUE TITLE
new release ?

### ISSUE THREAD

**Issue by dancinglightning** [rubygems/gems#36]
I noticed the gem switched from using yaml to json back in 2014
But the latest rubygems versions 0.8.3 is even older and uses yaml
any plans to release an update ?

T.

**Comment by sferik** [comment]
:shipit:

**Comment by dancinglightning** [comment]
hey @sferik, great.

A small breaking change though: the json api raises a JSON::ParserError, where the yaml returned a string ("This rubygem could not be found.") for non-existing gems.

This really seems to point to a rubygems.org bug, but i just thought i mention. Not sure how you want to deal with it. I would catch and return nil, but off course i fixed our code to catch now.

**Comment by sonalkr132** [comment]
On rubygems.org we recently [switched from `render :plain` to `render :text`](https://github.com/rubygems/rubygems.org/pull/1524) in preparation of rails 5 update. MIME type would have changed from `text/html` to `text/plain`.
