### ISSUE TITLE
Getting more than 50 top downloaded

### ISSUE THREAD

**Issue by mckaz** [rubygems/gems#48]
The `Gems#most_downloaded` method returns only the 50 most downloaded gems. Is there a way to increase that number? If so, it is not apparent in the doc/code. Thanks for your help!

**Comment by sonalkr132** [comment]
> Is there a way to increase that number? 

No, there isn't. Sorry.
You could use our [data dump](https://rubygems.org/pages/data) if liveness of data is not an issue for you.
